"""empty message

Revision ID: 31839f1a69cc
Revises: 
Create Date: 2022-04-18 18:48:45.177682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31839f1a69cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meme')
    # ### end Alembic commands ###
