"""empty message

Revision ID: 6accf57ebdf9
Revises: 70652e329606
Create Date: 2022-05-02 20:09:03.464278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6accf57ebdf9'
down_revision = '70652e329606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
