"""empty message

Revision ID: 70652e329606
Revises: 8dc951c225ca
Create Date: 2022-05-02 19:57:29.886210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70652e329606'
down_revision = '8dc951c225ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_message')
    # ### end Alembic commands ###
