"""empty message

Revision ID: 8dc951c225ca
Revises: f55990e21693
Create Date: 2022-05-01 17:43:49.852643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc951c225ca'
down_revision = 'f55990e21693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.String(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mention')
    # ### end Alembic commands ###
